import { Metadata } from "next";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: {
      url: "../../../public/favicon.ico",
      type: "image/png",
    },
    shortcut: { url: "../../../public/favicon.ico", type: "image/png" },
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

